#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           6
bspc config left_padding         1
bspc config right_padding        1

# Colors
bspc config focused_border_color "#17947C"
# bspc config normal_border_color  "#2D2D2D"
bspc config normal_border_color  "#1E2128"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gpick state=floating

# Set cursor theme
xsetroot -cursor_name left_ptr

# Polybar
killall polybar ; polybar mybar &
# Picom
#killall picom ; picom  --vsync --backend glx -CGb -o 0 -i 1 --unredir-if-possible --glx-no-stencil -D 8 --glx-no-rebind-pixmap -m 100 &
killall picom ; picom -b &
# Background
killall feh ; feh --bg-fill ~/dotfiles/wallpapers/conifer-sapling.jpg &
# Night light
# killall redshift ; killall redshift ; redshift -l 14.599512:120.984222 &
# Remap control key and caps lock
# xmodmap ~/.config/i3/swapkeys -display :0 &
# xrandr -s 1366x768 &
# Conky desktop monitor
#killall conky ; conky &

