#!/usr/bin/sh

# xinput set-prop 15 333 1 # was used on fedora installation
# Touchpad enabled
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1

sxhkd &
picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &	


bspc monitor -d I II III IV V

# bspc config border_width         0
# bspc config window_gap          0
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc config focused_border_color    "#8ec07c"
#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  1
bspc config window_gap                    2
bspc config top_padding                   25
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# setting wallpaper
nitrogen --set-scaled /home/david/Pictures/wallpapers/conifer-sapling.jpg

$HOME/.config/polybar/launch.sh
